export const FETCH_EXERCISES = 'FETCH_EXERCISES';
export const FETCH_EXERCISES_SELECTIVE = 'FETCH_EXERCISES_SELECTIVE';

export const CHANGE_ROUTE = 'CHANGE_ROUTE';
export const CHANGE_GENERATOR_ROUTE = 'CHANGE_GENERATOR_ROUTE';

export const PICK_WORKOUT_TYPE = 'PICK_WORKOUT_TYPE';
export const PICK_BODY_PARTS_MOVMENT_PATTERNS = 'PICK_BODY_PARTS_MOVMENT_PATTERNS';
export const PICK_BODY_PARTS = 'PICK_BODY_PARTS';
export const PICK_MOVMENT_PATTERNS = 'PICK_MOVMENT_PATTERNS';
export const PICK_WORKOUT_LEVEL = 'PICK_WORKOUT_LEVEL';
export const PICK_WORKOUT_EQUIPMENT = 'PICK_WORKOUT_EQUIPMENT';
export const PICK_SKILL_STRENGTH = 'PICK_SKILL_STRENGTH';
export const PICK_EXERCISE_NUMBER = 'PICK_EXERCISE_NUMBER';
